interface Options {
  inline: boolean
  rootName?: string
}

interface StructDef {
  name: string
  fields: string[]
}

export function jsonToGo(jsonStr: string, options: Options): string {
  const { inline, rootName = 'AutoGenerated' } = options

  let parsed: unknown
  try {
    parsed = JSON.parse(jsonStr)
  } catch {
    return '// Invalid JSON'
  }

  if (inline) {
    return generateInline(parsed, rootName, 0)
  }

  const structs: StructDef[] = []
  const rootType = generateFlat(parsed, rootName, structs)

  if (structs.length === 0) {
    return `type ${rootName} ${rootType}`
  }

  return structs
    .map((s) => `type ${s.name} struct {\n${s.fields.join('\n')}\n}`)
    .join('\n\n')
}

function goName(s: string): string {
  return s
    .replace(/[^a-zA-Z0-9_]/g, ' ')
    .split(/[\s_-]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

function singularize(s: string): string {
  if (s.endsWith('ies')) return s.slice(0, -3) + 'y'
  if (s.endsWith('ses') || s.endsWith('xes') || s.endsWith('zes')) return s.slice(0, -2)
  if (s.endsWith('s') && !s.endsWith('ss')) return s.slice(0, -1)
  return s + 'Item'
}

function jsonTag(key: string, omitempty: boolean): string {
  return omitempty ? `\`json:"${key},omitempty"\`` : `\`json:"${key}"\``
}

function goType(value: unknown): string {
  if (value === null) return 'interface{}'
  switch (typeof value) {
    case 'string': return 'string'
    case 'number': return Number.isInteger(value) ? 'int64' : 'float64'
    case 'boolean': return 'bool'
    default: return 'interface{}'
  }
}

function isPrimitive(value: unknown): boolean {
  return value === null || typeof value !== 'object'
}

// --- Inline mode ---

function generateInline(value: unknown, name: string, depth: number): string {
  if (value === null || value === undefined) {
    return `type ${name} interface{}`
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return `type ${name} []interface{}`
    const first = value[0]
    if (isPrimitive(first)) return `type ${name} []${goType(first)}`
    if (Array.isArray(first)) return `type ${name} [][]interface{}`

    const merged = mergeObjects(value.filter((v) => v && typeof v === 'object' && !Array.isArray(v)))
    const inner = generateInlineStruct(merged, depth)
    return `type ${name} []${inner}`
  }

  if (typeof value === 'object') {
    const inner = generateInlineStruct(value as Record<string, unknown>, depth)
    return `type ${name} ${inner}`
  }

  return `type ${name} ${goType(value)}`

  function generateInlineStruct(obj: Record<string, unknown>, d: number): string {
    const ind = '\t'.repeat(d)
    const innerInd = '\t'.repeat(d + 1)
    const keys = Object.keys(obj)
    if (keys.length === 0) return 'struct{}'

    const lines: string[] = []
    lines.push('struct {')

    for (const key of keys) {
      const val = obj[key]
      const fieldName = goName(key)

      if (val === null || val === undefined) {
        lines.push(`${innerInd}${fieldName} interface{} ${jsonTag(key, true)}`)
      } else if (Array.isArray(val)) {
        if (val.length === 0) {
          lines.push(`${innerInd}${fieldName} []interface{} ${jsonTag(key, false)}`)
        } else if (isPrimitive(val[0])) {
          lines.push(`${innerInd}${fieldName} []${goType(val[0])} ${jsonTag(key, false)}`)
        } else if (typeof val[0] === 'object' && !Array.isArray(val[0])) {
          const merged = mergeObjects(val.filter((v) => v && typeof v === 'object' && !Array.isArray(v)))
          const inner = generateInlineStruct(merged, d + 1)
          lines.push(`${innerInd}${fieldName} []${inner} ${jsonTag(key, false)}`)
        } else {
          lines.push(`${innerInd}${fieldName} []interface{} ${jsonTag(key, false)}`)
        }
      } else if (typeof val === 'object') {
        const inner = generateInlineStruct(val as Record<string, unknown>, d + 1)
        lines.push(`${innerInd}${fieldName} ${inner} ${jsonTag(key, false)}`)
      } else {
        lines.push(`${innerInd}${fieldName} ${goType(val)} ${jsonTag(key, false)}`)
      }
    }

    lines.push(`${ind}}`)
    return lines.join('\n')
  }
}

// --- Flat mode (separate type defs) ---

function generateFlat(value: unknown, name: string, structs: StructDef[]): string {
  if (value === null || value === undefined) return 'interface{}'

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]interface{}'
    const first = value[0]
    if (isPrimitive(first)) return `[]${goType(first)}`
    if (Array.isArray(first)) return '[][]interface{}'

    const merged = mergeObjects(value.filter((v) => v && typeof v === 'object' && !Array.isArray(v)))
    const itemName = singularize(name)
    generateFlatStruct(merged, itemName, structs)
    return `[]${itemName}`
  }

  if (typeof value === 'object') {
    generateFlatStruct(value as Record<string, unknown>, name, structs)
    return name
  }

  return goType(value)
}

function generateFlatStruct(obj: Record<string, unknown>, name: string, structs: StructDef[]): void {
  const fields: string[] = []
  const keys = Object.keys(obj)

  for (const key of keys) {
    const val = obj[key]
    const fieldName = goName(key)

    if (val === null || val === undefined) {
      fields.push(`\t${fieldName} interface{} ${jsonTag(key, true)}`)
    } else if (Array.isArray(val)) {
      if (val.length === 0) {
        fields.push(`\t${fieldName} []interface{} ${jsonTag(key, false)}`)
      } else if (isPrimitive(val[0])) {
        fields.push(`\t${fieldName} []${goType(val[0])} ${jsonTag(key, false)}`)
      } else if (typeof val[0] === 'object' && !Array.isArray(val[0])) {
        const merged = mergeObjects(val.filter((v) => v && typeof v === 'object' && !Array.isArray(v)))
        const itemName = singularize(goName(key))
        generateFlatStruct(merged, itemName, structs)
        fields.push(`\t${fieldName} []${itemName} ${jsonTag(key, false)}`)
      } else {
        fields.push(`\t${fieldName} []interface{} ${jsonTag(key, false)}`)
      }
    } else if (typeof val === 'object') {
      const childName = goName(key)
      generateFlatStruct(val as Record<string, unknown>, childName, structs)
      fields.push(`\t${fieldName} ${childName} ${jsonTag(key, false)}`)
    } else {
      fields.push(`\t${fieldName} ${goType(val)} ${jsonTag(key, false)}`)
    }
  }

  structs.push({ name, fields })
}

function mergeObjects(objects: Record<string, unknown>[]): Record<string, unknown> {
  const merged: Record<string, unknown> = {}
  for (const obj of objects) {
    for (const key of Object.keys(obj)) {
      if (!(key in merged)) {
        merged[key] = obj[key]
      }
    }
  }
  return merged
}
